name: Rust

on:
  push:
    branches:
      - main
      - release-*
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check fmt
        run: cargo fmt -- --check

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.82.0
      - run: cargo check

  minimal-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: cargo install cargo-hack cargo-minimal-versions
      - name: Install nightly rust
        uses: dtolnay/rust-toolchain@nightly
      - name: Check with minimal versions
        run: cargo minimal-versions check

  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
